# Generated by Django 3.1.7 on 2021-03-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0002_auto_20210327_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
